#ifndef CONVERT_H
#define CONVERT_H

enum LIFT_STATES
{
	LS_STOP,
	LS_MOVING_UP,
	LS_MOVING_DOWN,
	LS_OUT_OF_SERVICE,
	LS_OVERLOAD,
	LS_BUSY,
	LS_COLLECT_UP,
	LS_COLLECT_DOWN,
	LS_FIREMAN_CONTROL
};

enum LIFT_CODES
{
	LC_GRAY,
	LC_BINARY,
	LC_TTUP,
	LC_7SEG
};

enum LIFT_OPTIONS
{
	LO_FLOOR_COM	= 0x1,
	LO_FLAGS_COM 	= 0x2,
	LO_OVERLOAD		= 0x4,
};

#define SEGMENT_A		0x0001
#define SEGMENT_B		0x0002
#define SEGMENT_C		0x0004
#define SEGMENT_D		0x0008
#define SEGMENT_E		0x0010
#define SEGMENT_F		0x0020
#define SEGMENT_G		0x0040

#define SEGMENT_N		0x0080
#define SEGMENT_1 		0x0100
#define SEGMENT_2 		0x0200
#define ARROW_UP		0x0400
#define ARROW_DOWN		0x0800
#define BUSY			0x1000
#define OVERLOADED		0x1000
#define SERVICE			0x2000
#define BTN_FLAGS		0x4000
#define BTN_CODE		0x8000

#define TT_M1			0x0002
#define TT_817			0x0004
#define TT_818			0x0008

	
#define	SSEGMENT_MASK	(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_E|SEGMENT_F|SEGMENT_G)
#define	BINARY_MASK		(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_E)
#define	GRAY_MASK		(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_E)
	

#define	FLOOR_MASK (SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_E|SEGMENT_F|SEGMENT_G|SEGMENT_N|SEGMENT_1|SEGMENT_2)

#define	FLAGS_MASK (ARROW_UP|ARROW_DOWN|OVERLOADED|BUSY|SERVICE) 


//number definations
#define SEVEN_SEG_0	(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_E|SEGMENT_F)
#define SEVEN_SEG_1	(SEGMENT_B|SEGMENT_C)
#define SEVEN_SEG_2	(SEGMENT_A|SEGMENT_B|SEGMENT_D|SEGMENT_E|SEGMENT_G)
#define SEVEN_SEG_3	(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_G)
#define SEVEN_SEG_4	(SEGMENT_B|SEGMENT_C|SEGMENT_F|SEGMENT_G)
#define SEVEN_SEG_5	(SEGMENT_A|SEGMENT_C|SEGMENT_D|SEGMENT_F|SEGMENT_G)
#define SEVEN_SEG_6	(SEGMENT_A|SEGMENT_C|SEGMENT_D|SEGMENT_E|SEGMENT_F|SEGMENT_G)
#define SEVEN_SEG_7	(SEGMENT_A|SEGMENT_B|SEGMENT_C)
#define SEVEN_SEG_8	(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_E|SEGMENT_F|SEGMENT_G)
#define SEVEN_SEG_9	(SEGMENT_A|SEGMENT_B|SEGMENT_C|SEGMENT_D|SEGMENT_F|SEGMENT_G)
	

void convert( uint16_t data, int8_t* floor, uint32_t* state);

void set_ex_data(unsigned short dt);

#endif
